"""
OmniParse Architecture Study & Feature Analysis for Medical Handwriting OCR Enhancement
Generated by Z.ai | 2026-05-30
"""
import sys, os
PDF_SKILL_DIR = "/home/z/my-project/skills/pdf"
_scripts = os.path.join(PDF_SKILL_DIR, "scripts")
if _scripts not in sys.path:
    sys.path.insert(0, _scripts)

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_JUSTIFY
from reportlab.lib.units import inch, cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle,
    KeepTogether, HRFlowable
)
from reportlab.platypus.tableofcontents import TableOfContents
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.lib.utils import simpleSplit
import hashlib

# ━━ Font Registration ━━
pdfmetrics.registerFont(TTFont('Times New Roman', '/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf'))
pdfmetrics.registerFont(TTFont('Times New Roman Bold', '/usr/share/fonts/truetype/dejavu/DejaVuSerif-Bold.ttf'))
pdfmetrics.registerFont(TTFont('Calibri', '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'))
pdfmetrics.registerFont(TTFont('DejaVuSans', '/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf'))
pdfmetrics.registerFont(TTFont('SimHei', '/usr/share/fonts/truetype/chinese/SarasaMonoSC-Regular.ttf'))
registerFontFamily('Times New Roman', normal='Times New Roman', bold='Times New Roman Bold')
registerFontFamily('Calibri', normal='Calibri', bold='Calibri')
registerFontFamily('DejaVuSans', normal='DejaVuSans', bold='DejaVuSans')
registerFontFamily('SimHei', normal='SimHei', bold='SimHei')

# ━━ Color Palette ━━
ACCENT = colors.HexColor('#5635ba')
TEXT_PRIMARY = colors.HexColor('#1d1c1a')
TEXT_MUTED = colors.HexColor('#86837a')
BG_SURFACE = colors.HexColor('#e8e6e1')
BG_PAGE = colors.HexColor('#f1f0ef')
TABLE_HEADER_COLOR = ACCENT
TABLE_HEADER_TEXT = colors.white
TABLE_ROW_EVEN = colors.white
TABLE_ROW_ODD = BG_SURFACE

# ━━ Styles ━━
styles = {}

styles['Title'] = ParagraphStyle(
    name='Title', fontName='Times New Roman', fontSize=28,
    leading=36, alignment=TA_CENTER, textColor=TEXT_PRIMARY,
    spaceAfter=6
)
styles['Subtitle'] = ParagraphStyle(
    name='Subtitle', fontName='Times New Roman', fontSize=14,
    leading=20, alignment=TA_CENTER, textColor=TEXT_MUTED,
    spaceAfter=24
)
styles['H1'] = ParagraphStyle(
    name='H1', fontName='Times New Roman', fontSize=20,
    leading=28, textColor=ACCENT, spaceBefore=18, spaceAfter=12
)
styles['H2'] = ParagraphStyle(
    name='H2', fontName='Times New Roman', fontSize=16,
    leading=22, textColor=TEXT_PRIMARY, spaceBefore=14, spaceAfter=8
)
styles['H3'] = ParagraphStyle(
    name='H3', fontName='Times New Roman', fontSize=13,
    leading=18, textColor=TEXT_PRIMARY, spaceBefore=10, spaceAfter=6
)
styles['Body'] = ParagraphStyle(
    name='Body', fontName='Times New Roman', fontSize=10.5,
    leading=18, alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY,
    spaceBefore=0, spaceAfter=6
)
styles['BodyLeft'] = ParagraphStyle(
    name='BodyLeft', fontName='Times New Roman', fontSize=10.5,
    leading=18, alignment=TA_LEFT, textColor=TEXT_PRIMARY,
    spaceBefore=0, spaceAfter=6
)
styles['Bullet'] = ParagraphStyle(
    name='Bullet', fontName='Times New Roman', fontSize=10.5,
    leading=18, alignment=TA_LEFT, textColor=TEXT_PRIMARY,
    leftIndent=24, bulletIndent=12, spaceBefore=2, spaceAfter=2
)
styles['Code'] = ParagraphStyle(
    name='Code', fontName='DejaVuSans', fontSize=9,
    leading=14, alignment=TA_LEFT, textColor=colors.HexColor('#2d2d2d'),
    backColor=colors.HexColor('#f5f5f5'),
    leftIndent=12, rightIndent=12, spaceBefore=6, spaceAfter=6,
    borderWidth=0.5, borderColor=colors.HexColor('#cccccc'),
    borderPadding=6
)
styles['Caption'] = ParagraphStyle(
    name='Caption', fontName='Times New Roman', fontSize=9,
    leading=14, alignment=TA_CENTER, textColor=TEXT_MUTED,
    spaceBefore=3, spaceAfter=6
)
styles['TOC1'] = ParagraphStyle(
    name='TOC1', fontName='Times New Roman', fontSize=13,
    leading=20, leftIndent=20, spaceBefore=4, spaceAfter=2
)
styles['TOC2'] = ParagraphStyle(
    name='TOC2', fontName='Times New Roman', fontSize=11,
    leading=18, leftIndent=40, spaceBefore=2, spaceAfter=2
)

# Header and cell styles for tables
header_style = ParagraphStyle(
    name='TableHeader', fontName='Times New Roman', fontSize=10,
    textColor=colors.white, alignment=TA_CENTER
)
cell_style = ParagraphStyle(
    name='TableCell', fontName='Times New Roman', fontSize=9.5,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT, leading=14
)
cell_center = ParagraphStyle(
    name='TableCellCenter', fontName='Times New Roman', fontSize=9.5,
    textColor=TEXT_PRIMARY, alignment=TA_CENTER, leading=14
)

# ━━ Table helper ━━
def make_table(data, col_widths, available_w):
    """Create a styled table with proper widths."""
    t = Table(data, colWidths=col_widths, hAlign='CENTER')
    style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), TABLE_HEADER_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), TABLE_HEADER_TEXT),
        ('GRID', (0, 0), (-1, -1), 0.5, TEXT_MUTED),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]
    for i in range(1, len(data)):
        bg = TABLE_ROW_EVEN if i % 2 == 1 else TABLE_ROW_ODD
        style_cmds.append(('BACKGROUND', (0, i), (-1, i), bg))
    t.setStyle(TableStyle(style_cmds))
    return t


# ━━ TocDocTemplate ━━
class TocDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, 'bookmark_name'):
            level = getattr(flowable, 'bookmark_level', 0)
            text = getattr(flowable, 'bookmark_text', '')
            key = getattr(flowable, 'bookmark_key', '')
            self.notify('TOCEntry', (level, text, self.page, key))

# ━━ Heading helpers ━━
available_height = A4[1] - 1.0*inch - 1.0*inch
H1_ORPHAN_THRESHOLD = available_height * 0.15

from reportlab.platypus import CondPageBreak

def add_heading(text, style, level=0):
    key = 'h_%s' % hashlib.md5(text.encode()).hexdigest()[:8]
    p = Paragraph('<a name="%s"/>%s' % (key, text), style)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    return p

def add_major_section(text, style):
    return [
        CondPageBreak(H1_ORPHAN_THRESHOLD),
        add_heading(text, style, level=0),
    ]

def safe_keep(elements):
    total_h = 0
    for el in elements:
        w, h = el.wrap(A4[0] - 2*inch, A4[1])
        total_h += h
    if total_h <= available_height * 0.4:
        return [KeepTogether(elements)]
    elif len(elements) >= 2:
        return [KeepTogether(elements[:2])] + list(elements[2:])
    return list(elements)


# ━━ Build Document ━━
OUTPUT = "/home/z/my-project/download/omniparse_analysis_body.pdf"

doc = TocDocTemplate(
    OUTPUT,
    pagesize=A4,
    leftMargin=1.0*inch, rightMargin=1.0*inch,
    topMargin=1.0*inch, bottomMargin=1.0*inch,
    title="OmniParse Architecture Study and Feature Analysis",
    author="Z.ai",
    creator="Z.ai",
    subject="Analysis of OmniParse for Medical Handwriting OCR Enhancement"
)

avail_w = A4[0] - 2*inch  # ~451pt

story = []

# ── TOC ──
story.append(Paragraph('<b>Table of Contents</b>', styles['H1']))
story.append(Spacer(1, 12))
toc = TableOfContents()
toc.levelStyles = [styles['TOC1'], styles['TOC2']]
story.append(toc)
story.append(PageBreak())

# ═══════════════════════════════════════════
# 1. EXECUTIVE SUMMARY
# ═══════════════════════════════════════════
story.extend(add_major_section('<b>1. Executive Summary</b>', styles['H1']))

story.append(Paragraph(
    'This document presents a comprehensive architectural study and feature analysis of the OmniParse project '
    '(<b>github.com/adithya-s-k/omniparse</b>), an open-source document parsing and data ingestion platform developed by Adithya S K. '
    'The study specifically examines how OmniParse\'s multi-modal parsing capabilities, its underlying AI model architecture, and its modular '
    'design patterns can be strategically leveraged to enhance the Medical Handwriting OCR system currently under development at '
    '<b>github.com/DrAbdulmalek/medical-handwriting-ocr</b> (version 3.2.0, 97% production readiness).',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph(
    'The Medical Handwriting OCR project is a production-grade system built on FastAPI, PaddleOCR, TrOCR, and a sophisticated '
    'six-strategy suggestion engine with UMLS/SNOMED-CT medical terminology validation. It supports Arabic medical handwriting recognition '
    'and includes continual learning with Elastic Weight Consolidation (EWC) and Replay Buffer mechanisms. The system already encompasses '
    'over 150 files, 8 API routers, 7 ORM models, and a full Docker/K8s/Terraform deployment pipeline.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph(
    'OmniParse, on the other hand, provides a unified platform for converting unstructured data across documents, images, audio, '
    'video, and web pages into structured markdown optimized for generative AI applications. Its architecture leverages Surya OCR, '
    'Florence-2 vision model, Whisper for audio transcription, and Marker for PDF conversion. The platform operates entirely locally '
    'and is deployable via Docker with GPU support (T4 8GB minimum). This analysis identifies 12 specific integration opportunities '
    'across document parsing, image processing, multi-modal ingestion, text chunking, and web crawling that could significantly '
    'augment the medical OCR system\'s capabilities.',
    styles['Body']
))
story.append(Spacer(1, 6))

# Key findings table
story.append(Paragraph('<b>Key Findings at a Glance</b>', styles['H3']))
kf_data = [
    [Paragraph('<b>Dimension</b>', header_style), Paragraph('<b>OmniParse Feature</b>', header_style), Paragraph('<b>Integration Potential</b>', header_style)],
    [Paragraph('Document Parsing', cell_style), Paragraph('Marker + Surya OCR + Florence-2 pipeline', cell_style), Paragraph('High - PDF/image pre-processing for handwritten prescriptions', cell_style)],
    [Paragraph('Image Processing', cell_style), Paragraph('Multi-task vision (OCR, caption, object detection)', cell_style), Paragraph('High - Document layout analysis and region detection', cell_style)],
    [Paragraph('Audio Processing', cell_style), Paragraph('Whisper-based transcription', cell_style), Paragraph('Medium - Voice-to-text for dictation integration', cell_style)],
    [Paragraph('Text Chunking', cell_style), Paragraph('Regex, NLP, sliding window strategies', cell_style), Paragraph('Medium - Extracted text segmentation for RAG', cell_style)],
    [Paragraph('Web Crawling', cell_style), Paragraph('Selenium-based with HTML-to-Markdown', cell_style), Paragraph('Low - Medical literature ingestion', cell_style)],
    [Paragraph('Modular Architecture', cell_style), Paragraph('Strategy pattern, shared state, plugin routers', cell_style), Paragraph('High - Architecture reference for extensibility', cell_style)],
]
story.append(Spacer(1, 12))
t = make_table(kf_data, [avail_w*0.20, avail_w*0.40, avail_w*0.40], avail_w)
story.append(t)
story.append(Paragraph('Table 1: Key findings summary of OmniParse integration opportunities', styles['Caption']))

# ═══════════════════════════════════════════
# 2. PROJECT OVERVIEW
# ═══════════════════════════════════════════
story.extend(add_major_section('<b>2. Project Overview: OmniParse</b>', styles['H1']))

story.append(Paragraph(
    'OmniParse is a unified data ingestion and parsing platform designed to transform unstructured data from diverse '
    'sources into structured, actionable output optimized for Large Language Model (LLM) applications such as Retrieval-Augmented '
    'Generation (RAG), fine-tuning, and knowledge base construction. The project was created by Adithya S Kolavi and has gained '
    'significant traction in the open-source community as a comprehensive solution for the common challenge of multi-format data processing. '
    'The platform currently supports approximately 20 different file types and is designed to run entirely on local hardware, requiring '
    'no external API dependencies.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>2.1 Core Capabilities</b>', styles['H2']))
story.append(Paragraph(
    'The OmniParse platform provides four primary processing modules, each designed to handle a distinct category of unstructured data. '
    'These modules operate through a unified FastAPI server with a Gradio-based interactive web interface. The document parsing module handles '
    'PDF, PowerPoint (.ppt, .pptx), and Word (.doc, .docx) files, converting them to structured markdown with embedded image extraction. '
    'The image processing module supports OCR extraction, image captioning at three granularity levels, object detection, dense region '
    'captioning, region proposal generation, and even referring expression segmentation. The media module processes both audio files '
    '(.mp3, .wav, .aac) through Whisper-based transcription and video files (.mp4, .mkv, .avi, .mov) by first extracting the audio '
    'track and then transcribing it. Finally, the web crawling module uses Selenium-based dynamic page rendering to convert web pages '
    'into structured markdown with metadata extraction, link classification, and media detection.',
    styles['Body']
))
story.append(Spacer(1, 6))

# Supported file types table
story.append(Paragraph('<b>2.2 Supported Data Types</b>', styles['H2']))
ft_data = [
    [Paragraph('<b>Category</b>', header_style), Paragraph('<b>Extensions</b>', header_style), Paragraph('<b>Processing Pipeline</b>', header_style)],
    [Paragraph('Documents', cell_center), Paragraph('.pdf, .doc, .docx, .ppt, .pptx', cell_center), Paragraph('LibreOffice conversion + Marker + Surya OCR', cell_center)],
    [Paragraph('Images', cell_center), Paragraph('.png, .jpg, .jpeg, .tiff, .bmp, .heic', cell_center), Paragraph('Florence-2 multi-task vision model', cell_center)],
    [Paragraph('Video', cell_center), Paragraph('.mp4, .mkv, .avi, .mov', cell_center), Paragraph('MoviePy audio extraction + Whisper', cell_center)],
    [Paragraph('Audio', cell_center), Paragraph('.mp3, .wav, .aac', cell_center), Paragraph('OpenAI Whisper transcription', cell_center)],
    [Paragraph('Web Pages', cell_center), Paragraph('Any HTTP/HTTPS URL', cell_center), Paragraph('Selenium + BeautifulSoup + html2text', cell_center)],
]
story.append(Spacer(1, 12))
t = make_table(ft_data, [avail_w*0.18, avail_w*0.35, avail_w*0.47], avail_w)
story.append(t)
story.append(Paragraph('Table 2: OmniParse supported data types and processing pipelines', styles['Caption']))

# ═══════════════════════════════════════════
# 3. ARCHITECTURE ANALYSIS
# ═══════════════════════════════════════════
story.extend(add_major_section('<b>3. Architecture Analysis</b>', styles['H1']))

story.append(Paragraph('<b>3.1 System Architecture</b>', styles['H2']))
story.append(Paragraph(
    'OmniParse follows a modular, layered architecture built on FastAPI as the web framework. The system is organized around four '
    'primary processing domains: documents, images, media, and web content. Each domain is implemented as a self-contained module '
    'with its own router, business logic, and utility functions. The central orchestration happens in the <b>server.py</b> entry point, '
    'which initializes the FastAPI application, configures CORS middleware, mounts the Gradio demo UI, and conditionally includes '
    'routers based on command-line arguments. This conditional loading is a particularly thoughtful design choice that allows '
    'users to run only the components they need, reducing memory footprint when GPU resources are limited.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph(
    'The core architectural pattern revolves around a <b>SharedState</b> singleton model implemented through a Pydantic BaseModel. '
    'This shared state holds references to all loaded AI models (OCR models, vision models, Whisper, web crawler) and is accessible '
    'across all router modules. The model loading happens at startup through the <b>load_omnimodel()</b> function, which initializes '
    'different model sets based on command-line flags (--documents, --media, --web). This approach ensures that models are loaded '
    'exactly once and shared across all request handlers, which is critical for GPU memory management given the substantial memory '
    'requirements of the underlying models.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>3.2 AI Model Stack</b>', styles['H2']))
story.append(Paragraph(
    'The AI model stack in OmniParse is carefully curated from state-of-the-art open-source models. For document parsing, it relies '
    'on the <b>Marker</b> library (by VikParuchuri), which itself uses the <b>Surya OCR</b> series of models for text recognition, '
    'layout detection, reading order detection, and equation recognition (via Texify). Marker converts PDFs to high-quality markdown '
    'while preserving structure, tables, and images. For image processing, OmniParse uses <b>Florence-2 base</b> from Microsoft, a '
    'unified vision-language model capable of performing over 15 different visual tasks including OCR, captioning, object detection, '
    'segmentation, and region proposal. For audio/video transcription, it uses <b>OpenAI Whisper Small</b>, providing speech-to-text '
    'capabilities across multiple languages. The web crawling module additionally includes <b>BERT</b>, <b>BGE-small-en</b>, and '
    '<b>RoBERTa</b> models for text classification, embedding generation, and topic detection respectively.',
    styles['Body']
))
story.append(Spacer(1, 6))

# Model stack table
ms_data = [
    [Paragraph('<b>Model</b>', header_style), Paragraph('<b>Provider</b>', header_style), Paragraph('<b>Purpose</b>', header_style), Paragraph('<b>Task Types</b>', header_style)],
    [Paragraph('Surya OCR', cell_center), Paragraph('VikParuchuri', cell_center), Paragraph('Document text extraction', cell_center), Paragraph('OCR, layout, reading order, equations', cell_center)],
    [Paragraph('Marker', cell_center), Paragraph('VikParuchuri', cell_center), Paragraph('PDF-to-Markdown conversion', cell_center), Paragraph('Structure preservation, table extraction', cell_center)],
    [Paragraph('Florence-2 Base', cell_center), Paragraph('Microsoft', cell_center), Paragraph('Multi-task vision processing', cell_center), Paragraph('OCR, caption, OD, segmentation, region', cell_center)],
    [Paragraph('Whisper Small', cell_center), Paragraph('OpenAI', cell_center), Paragraph('Audio/video transcription', cell_center), Paragraph('Speech-to-text, multi-language', cell_center)],
    [Paragraph('BERT Base', cell_center), Paragraph('Google', cell_center), Paragraph('Text embedding', cell_center), Paragraph('Semantic similarity for web content', cell_center)],
    [Paragraph('RoBERTa Topic', cell_center), Paragraph('CardiffNLP', cell_center), Paragraph('Topic classification', cell_center), Paragraph('Content categorization', cell_center)],
]
story.append(Spacer(1, 12))
t = make_table(ms_data, [avail_w*0.20, avail_w*0.18, avail_w*0.28, avail_w*0.34], avail_w)
story.append(t)
story.append(Paragraph('Table 3: AI model stack used by OmniParse', styles['Caption']))

story.append(Spacer(1, 12))
story.append(Paragraph('<b>3.3 Request Processing Flow</b>', styles['H2']))
story.append(Paragraph(
    'The request processing in OmniParse follows a clean pipeline pattern. For document parsing, the flow begins with file upload '
    'via FastAPI\'s UploadFile, which reads the file bytes into memory. For non-PDF documents (Word, PowerPoint), the system first '
    'converts them to PDF using LibreOffice\'s headless mode, then passes the PDF bytes to Marker\'s <b>convert_single_pdf()</b> '
    'function. This function performs a multi-stage pipeline: page rendering via pdfium, text extraction with OCR fallback using '
    'Surya models, table structure detection, image extraction, and finally markdown generation. The result is a <b>responseDocument</b> '
    'Pydantic model containing the extracted text, a list of base64-encoded images, and metadata about the parsing process.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph(
    'For image processing, OmniParse offers two distinct paths. The <b>parse_image</b> endpoint converts images to PDF using img2pdf '
    'and then processes them through the same Marker pipeline, suitable for extracting text from photographed documents. The '
    '<b>process_image</b> endpoint takes a different approach, using Florence-2 directly on the raw image to perform specific visual '
    'tasks. This endpoint accepts a task parameter that maps to specific Florence-2 prompt tokens, enabling capabilities such as OCR '
    '(using the &lt;OCR&gt; token), OCR with bounding box regions (&lt;OCR_WITH_REGION&gt;), image captioning at three levels '
    'of detail, object detection (&lt;OD&gt;), dense region captioning, and even referring expression segmentation. The results are '
    'returned with annotated images where applicable.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>3.4 Web Crawling Architecture</b>', styles['H2']))
story.append(Paragraph(
    'The web crawling subsystem implements a strategy pattern through the abstract <b>CrawlerStrategy</b> class, currently with a '
    '<b>LocalSeleniumCrawlerStrategy</b> concrete implementation. This design allows for future extensions such as cloud-based '
    'crawling services or headless browser alternatives. The WebCrawler class manages the crawling lifecycle: it navigates to the '
    'target URL using Selenium with headless Chrome, waits for page load completion, optionally executes custom JavaScript code, '
    'captures the raw HTML, and then processes it through a sophisticated HTML cleaning pipeline. The cleaning pipeline, implemented '
    'in the web utilities module, performs tag decomposition (removing scripts, styles, metadata), content extraction with word count '
    'thresholding, empty element pruning, nested element flattening, CSS selector-based content targeting, metadata extraction '
    '(Open Graph, Twitter Cards), and finally conversion to markdown via a custom html2text implementation. The result includes '
    'structured markdown, cleaned HTML, internal/external link classification, media references, and an optional screenshot.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>3.5 Chunking Strategies</b>', styles['H2']))
story.append(Paragraph(
    'OmniParse implements a well-designed text chunking subsystem using the Strategy pattern with an abstract base class '
    '<b>ChunkingStrategy</b>. The system provides four concrete implementations: <b>RegexChunking</b> which splits text based on '
    'configurable regex patterns (defaulting to double newlines for paragraph detection), <b>NlpSentenceChunking</b> which uses '
    'NLTK\'s sentence tokenizer for linguistically-aware sentence splitting, <b>FixedLengthWordChunking</b> which creates chunks of '
    'a specified word count, and <b>SlidingWindowChunking</b> which creates overlapping chunks with configurable window size and step. '
    'Additionally, there is a <b>TopicSegmentationChunking</b> class designed to use NLTK\'s TextTiling algorithm for topic-based '
    'segmentation, though it has a minor bug in the implementation (using "nl.toknize" instead of "nltk.tokenize"). These chunking '
    'strategies are particularly relevant for preparing parsed content for RAG (Retrieval-Augmented Generation) pipelines.',
    styles['Body']
))
story.append(Spacer(1, 6))

# Chunking strategies table
cs_data = [
    [Paragraph('<b>Strategy</b>', header_style), Paragraph('<b>Method</b>', header_style), Paragraph('<b>Best For</b>', header_style), Paragraph('<b>Configurability</b>', header_style)],
    [Paragraph('Regex', cell_center), Paragraph('Pattern-based splitting', cell_center), Paragraph('Structured text with clear delimiters', cell_center), Paragraph('Custom regex patterns', cell_center)],
    [Paragraph('NLP Sentence', cell_center), Paragraph('NLTK sentence tokenizer', cell_center), Paragraph('Natural language text', cell_center), Paragraph('Fixed', cell_center)],
    [Paragraph('Topic Segmentation', cell_center), Paragraph('NLTK TextTiling', cell_center), Paragraph('Long documents with topic shifts', cell_center), Paragraph('Num keywords', cell_center)],
    [Paragraph('Fixed Length', cell_center), Paragraph('Word count windows', cell_center), Paragraph('Uniform chunking for embeddings', cell_center), Paragraph('Chunk size parameter', cell_center)],
    [Paragraph('Sliding Window', cell_center), Paragraph('Overlapping word windows', cell_center), Paragraph('Context preservation across chunks', cell_center), Paragraph('Window size + step', cell_center)],
]
story.append(Spacer(1, 12))
t = make_table(cs_data, [avail_w*0.22, avail_w*0.28, avail_w*0.28, avail_w*0.22], avail_w)
story.append(t)
story.append(Paragraph('Table 4: OmniParse text chunking strategies comparison', styles['Caption']))

# ═══════════════════════════════════════════
# 4. CODEBASE DEEP DIVE
# ═══════════════════════════════════════════
story.extend(add_major_section('<b>4. Codebase Deep Dive</b>', styles['H1']))

story.append(Paragraph('<b>4.1 Project Structure</b>', styles['H2']))
story.append(Paragraph(
    'The OmniParse project follows a clean, modular Python package structure. The root directory contains the main entry point '
    '(server.py), project configuration (pyproject.toml with Poetry dependencies), Docker configuration, and the omniparse package '
    'directory. The omniparse package itself is organized into five domain modules: documents, image, media, web, and chunking, each '
    'with its own __init__.py, router.py, and utility files. There is also a models module containing the shared Pydantic response '
    'models, and a utils module for common utilities like image encoding and ASCII art generation. Additionally, the project includes '
    'a python-sdk subdirectory with an async client library (AsyncOmniParse) using httpx for non-blocking API interactions, and a '
    'docs directory with GitBook-style documentation covering installation, API reference, deployment, integration examples with '
    'LangChain and LlamaIndex, and a Google Colab notebook for quick experimentation.',
    styles['Body']
))
story.append(Spacer(1, 6))

# File structure table
story.append(Paragraph('<b>4.2 Key Source Files</b>', styles['H2']))
fs_data = [
    [Paragraph('<b>File</b>', header_style), Paragraph('<b>Lines</b>', header_style), Paragraph('<b>Responsibility</b>', header_style)],
    [Paragraph('server.py', cell_style), Paragraph('89', cell_center), Paragraph('FastAPI app initialization, CORS, Gradio mount, router inclusion', cell_style)],
    [Paragraph('omniparse/__init__.py', cell_style), Paragraph('76', cell_center), Paragraph('SharedState model, load_omnimodel(), model lifecycle management', cell_style)],
    [Paragraph('omniparse/demo.py', cell_style), Paragraph('730', cell_center), Paragraph('Full Gradio UI with 4 tabs (Documents, Images, Media, Web)', cell_style)],
    [Paragraph('omniparse/models/__init__.py', cell_style), Paragraph('64', cell_center), Paragraph('responseDocument and responseImage Pydantic models', cell_style)],
    [Paragraph('omniparse/chunking/__init__.py', cell_style), Paragraph('114', cell_center), Paragraph('5 chunking strategy classes with abstract base', cell_style)],
    [Paragraph('omniparse/image/process.py', cell_style), Paragraph('188', cell_center), Paragraph('Florence-2 task routing, vision model inference pipeline', cell_style)],
    [Paragraph('omniparse/web/web_crawler.py', cell_style), Paragraph('202', cell_center), Paragraph('WebCrawler orchestration, HTML processing, metadata extraction', cell_style)],
    [Paragraph('omniparse/web/utils.py', cell_style), Paragraph('646', cell_center), Paragraph('HTML cleaning, markdown conversion, LLM block extraction', cell_style)],
    [Paragraph('omniparse/media/__init__.py', cell_style), Paragraph('98', cell_center), Paragraph('Audio parsing and video-to-audio extraction + transcription', cell_style)],
    [Paragraph('omniparse/documents/router.py', cell_style), Paragraph('199', cell_center), Paragraph('PDF/PPT/DOC parsing endpoints with LibreOffice conversion', cell_style)],
    [Paragraph('python-sdk/omniparse_client/omniparse.py', cell_style), Paragraph('455', cell_center), Paragraph('Async client with typed methods for all endpoints', cell_style)],
]
story.append(Spacer(1, 12))
t = make_table(fs_data, [avail_w*0.40, avail_w*0.08, avail_w*0.52], avail_w)
story.append(t)
story.append(Paragraph('Table 5: OmniParse key source files and their responsibilities', styles['Caption']))

story.append(Spacer(1, 12))
story.append(Paragraph('<b>4.3 Data Model Design</b>', styles['H2']))
story.append(Paragraph(
    'OmniParse\'s data model is elegantly simple yet flexible. The central response model is <b>responseDocument</b>, a Pydantic '
    'BaseModel with four fields: <b>text</b> (the extracted/processed text content), <b>images</b> (a list of responseImage objects), '
    '<b>metadata</b> (a flexible dictionary for arbitrary metadata), and <b>chunks</b> (a list of text segments from chunking). '
    'The <b>responseImage</b> model contains the base64-encoded image data, an image name, and optional image info dictionary. '
    'The responseDocument class provides convenience methods: <b>add_image()</b> which accepts either base64 strings or PIL Image '
    'objects and automatically encodes them, <b>encode_image_to_base64()</b> for image conversion, <b>image_processor()</b> for '
    'batch image captioning, and <b>chunk_text()</b> for applying a chunking strategy to the document text. This unified response '
    'model ensures consistent API output regardless of the input type, which is a design principle worth adopting.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>4.4 Dependency Management</b>', styles['H2']))
story.append(Paragraph(
    'The project uses Poetry for dependency management with a carefully selected set of 31 dependencies organized around the core '
    'functionality areas. The OCR/document processing stack includes surya-ocr, texify, marker-pdf, pdftext, and pypdfium2. '
    'The vision model stack relies on transformers, torch, flash-attn, and timm. The audio processing uses openai-whisper and moviepy. '
    'The web crawling stack depends on selenium, webdriver-manager, beautifulsoup4, and html2text. The API layer uses FastAPI with '
    'uvicorn, while the UI layer uses Gradio. Notably, the project pins torch to version 2.2.2 due to a known incompatibility with '
    'vision models in torch 2.3.0, demonstrating careful attention to dependency compatibility. The entire project requires '
    'Python 3.10+ and a GPU with 8-10 GB minimum VRAM for optimal performance.',
    styles['Body']
))
story.append(Spacer(1, 6))

# ═══════════════════════════════════════════
# 5. INTEGRATION OPPORTUNITIES FOR MEDICAL OCR
# ═══════════════════════════════════════════
story.extend(add_major_section('<b>5. Integration Opportunities for Medical Handwriting OCR</b>', styles['H1']))

story.append(Paragraph(
    'This section represents the core contribution of this study: a detailed analysis of specific OmniParse features that can be '
    'adapted and integrated into the Medical Handwriting OCR system to enhance its capabilities. Each opportunity is evaluated '
    'based on technical feasibility, expected impact, and implementation complexity.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>5.1 Enhanced Document Pre-Processing Pipeline</b>', styles['H2']))
story.append(Paragraph(
    'The most significant integration opportunity lies in OmniParse\'s document parsing pipeline, which combines Marker\'s PDF '
    'processing with Surya OCR for a robust two-stage extraction approach. The Medical OCR project currently processes uploaded '
    'images directly through PaddleOCR and TrOCR. By adopting OmniParse\'s approach of first converting diverse document formats '
    'to a normalized PDF representation using LibreOffice\'s headless mode, then applying structure-aware parsing through Marker, '
    'the system could handle a much wider range of medical document formats including scanned prescriptions, lab reports, discharge '
    'summaries, and referral letters. Marker\'s ability to detect and preserve table structures would be particularly valuable for '
    'parsing medical lab results and medication tables. The implementation would involve adding a pre-processing step in the upload '
    'router that normalizes all input formats to PDF before passing them to the existing OCR pipeline.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>5.2 Florence-2 Multi-Task Vision for Layout Analysis</b>', styles['H2']))
story.append(Paragraph(
    'OmniParse\'s use of Florence-2 as a unified multi-task vision model is architecturally elegant and directly applicable to '
    'medical handwriting recognition. Currently, the Medical OCR system uses PaddleOCR for initial text detection and TrOCR for '
    'recognition, but lacks a dedicated layout analysis component. Florence-2\'s <b>&lt;REGION_PROPOSAL&gt;</b> task could identify '
    'discrete regions within a prescription image (signature blocks, dosage fields, patient information sections), while its '
    '<b>&lt;OD&gt;</b> (Object Detection) task could locate specific medical document elements like stamps, seals, barcodes, or QR '
    'codes. The <b>&lt;OCR_WITH_REGION&gt;</b> task is particularly promising as it provides both text content and bounding box '
    'coordinates, which could supplement the existing PaddleOCR text detection with more semantically aware region identification. '
    'Furthermore, Florence-2\'s <b>&lt;DENSE_REGION_CAPTION&gt;</b> could provide contextual descriptions of document regions, helping '
    'disambiguate handwritten medication names from dosage instructions.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>5.3 Unified Response Model</b>', styles['H2']))
story.append(Paragraph(
    'OmniParse\'s <b>responseDocument</b> Pydantic model provides a clean, extensible pattern for standardized API responses. The '
    'Medical OCR project could benefit from adopting a similar unified response model that normalizes output across different processing '
    'pipelines. Currently, the medical OCR system returns results through various formats depending on the endpoint. A unified model '
    'like responseDocument that always includes extracted text, associated images (crop regions, annotated images), processing metadata '
    '(confidence scores, model versions, processing time), and optional text chunks would create a more consistent and developer-friendly '
    'API. The Pydantic-based design also enables automatic OpenAPI schema generation and client-side validation, which aligns well '
    'with the existing FastAPI infrastructure of the medical OCR project.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>5.4 Text Chunking for Medical RAG Integration</b>', styles['H2']))
story.append(Paragraph(
    'OmniParse\'s implementation of multiple chunking strategies through the Strategy pattern is directly applicable to the medical '
    'OCR system\'s RAG capabilities. The Medical OCR project already includes a suggestion engine with six strategies, but lacks a '
    'dedicated text chunking module for preparing extracted text for retrieval. By adapting OmniParse\'s chunking framework, the '
    'medical system could implement domain-specific chunking strategies such as: medication-based chunking (splitting prescription '
    'text around detected medication names), section-based chunking (patient info vs. diagnosis vs. treatment), and semantic '
    'chunking using medical embeddings. The SlidingWindowChunking strategy would be particularly useful for preserving context around '
    'medical abbreviations, while the NLP sentence chunking could be enhanced with Arabic-specific sentence boundary detection to '
    'handle the RTL (right-to-left) nature of Arabic medical text.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>5.5 Audio/Video Dictation Processing</b>', styles['H2']))
story.append(Paragraph(
    'OmniParse\'s audio processing module, built on OpenAI Whisper, presents a compelling opportunity to add voice input capabilities '
    'to the Medical OCR system. Physicians frequently use voice dictation for medical notes, and many medical records include '
    'audio annotations. By integrating a Whisper-based transcription endpoint, the system could accept audio recordings of medical '
    'dictation, transcribe them to text, and then pass the transcribed text through the existing suggestion engine for medical '
    'terminology validation and correction. This would significantly expand the system\'s input modalities beyond handwritten and '
    'printed text. The implementation could leverage the medical OCR project\'s existing Celery task infrastructure for asynchronous '
    'processing of longer audio recordings, with Whisper\'s small model providing a good balance between accuracy and resource '
    'requirements. Additionally, the video processing pipeline (extracting audio from video and transcribing it) could support '
    'processing of telemedicine recordings and medical training videos.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>5.6 Web Crawling for Medical Literature Ingestion</b>', styles['H2']))
story.append(Paragraph(
    'OmniParse\'s Selenium-based web crawler with its HTML-to-markdown conversion pipeline could be adapted to create a medical '
    'literature ingestion subsystem. Medical professionals often need to cross-reference handwritten prescriptions with online drug '
    'databases, clinical guidelines, and pharmaceutical information. By integrating a web crawling capability, the medical OCR system '
    'could automatically fetch relevant medical literature, parse it into structured text, and incorporate it into the suggestion '
    'engine\'s context. The crawler\'s CSS selector support would allow targeted extraction from specific medical websites, while '
    'the metadata extraction capabilities could capture publication dates, author information, and source credibility indicators. '
    'However, this integration has lower priority compared to the core OCR enhancements due to the specialized nature of medical '
    'web resources and potential licensing considerations.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>5.7 Modular Router Architecture Pattern</b>', styles['H2']))
story.append(Paragraph(
    'OmniParse\'s architectural pattern of separating each processing domain into its own FastAPI router module, combined with '
    'the shared state singleton for model management, is a design pattern that the Medical OCR project could further adopt. While '
    'the medical OCR project already has a well-organized router structure with 8 routers, the OmniParse pattern of conditional '
    'router inclusion based on configuration flags could optimize resource usage in deployment scenarios where not all features '
    'are needed. For example, a deployment focused only on prescription OCR might not need the DICOM processing or UMLS validation '
    'routers, and being able to exclude them would reduce memory footprint and attack surface. The shared state pattern also '
    'provides a clean mechanism for managing model lifecycle across routers without resorting to global variables.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>5.8 Advanced Image Annotation and Visualization</b>', styles['H2']))
story.append(Paragraph(
    'OmniParse\'s image utility module provides sophisticated visualization capabilities for image processing results. The '
    '<b>draw_ocr_bboxes()</b> function renders colored polygon overlays on detected text regions with labels, while '
    '<b>draw_polygons()</b> handles segmentation masks with fill options. The <b>plot_bbox()</b> function creates matplotlib-based '
    'bounding box visualizations for object detection results. These visualization tools could significantly enhance the Medical '
    'OCR system\'s feedback mechanisms by providing annotated output images that show exactly where text was detected, what regions '
    'were classified as handwritten vs. printed, and how the document was segmented for processing. This would be particularly '
    'valuable for the correction workflow, allowing users to see the model\'s interpretation of the document alongside the raw '
    'extracted text. The frontend could display these annotated images using the existing crop storage infrastructure.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>5.9 Gradio Interactive UI Reference</b>', styles['H2']))
story.append(Paragraph(
    'OmniParse\'s Gradio-based demo interface provides a useful reference for building interactive testing interfaces. While the '
    'Medical OCR project already has a production React/Vite frontend and an HTML/CSS/JS MVP, a lightweight Gradio-based testing '
    'interface could accelerate development and debugging. The Gradio UI demonstrates effective patterns for multi-tab organization '
    '(Documents, Images, Media, Web), file upload handling with format validation, real-time result display with galleries and '
    'JSON output viewers, and API documentation panels with curl/python/JavaScript examples. This rapid prototyping approach allows '
    'developers to test new OCR pipelines without modifying the production frontend. The Gradio interface could be mounted as a '
    'separate development-only route in the FastAPI application, similar to OmniParse\'s approach of mounting it at the root path.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>5.10 Batch Processing and Async Client SDK</b>', styles['H2']))
story.append(Paragraph(
    'OmniParse\'s Python SDK, particularly the <b>AsyncOmniParse</b> class, demonstrates an excellent pattern for building client '
    'libraries for the Medical OCR API. The async client uses httpx for non-blocking HTTP requests, implements file type validation, '
    'and provides typed methods for each endpoint. The Medical OCR project\'s API documentation already describes SDK usage patterns, '
    'but a formal client library following OmniParse\'s pattern would lower the barrier for third-party integrations. Key features '
    'to adopt include: automatic file type validation before upload, configurable timeout and retry logic, support for saving parsed '
    'results to the local filesystem, and a clean separation between synchronous and asynchronous usage patterns. The client library '
    'could be packaged as a separate pip-installable package, making it easier for healthcare applications to integrate with the '
    'medical OCR system.',
    styles['Body']
))
story.append(Spacer(1, 6))

# ═══════════════════════════════════════════
# 6. RECOMMENDED INTEGRATION ROADMAP
# ═══════════════════════════════════════════
story.extend(add_major_section('<b>6. Recommended Integration Roadmap</b>', styles['H1']))

story.append(Paragraph(
    'Based on the analysis presented in the preceding sections, this chapter proposes a phased integration roadmap that prioritizes '
    'high-impact, feasible enhancements while building toward a more comprehensive multi-modal medical data processing platform. '
    'The roadmap is organized into three phases, each building upon the capabilities established in the previous phase.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>6.1 Phase 1: Core OCR Enhancement (Short-Term)</b>', styles['H2']))
story.append(Paragraph(
    'The first phase focuses on integrating the most immediately impactful features from OmniParse into the medical OCR pipeline. '
    'This phase requires minimal architectural changes and can be implemented within the existing system framework. The primary tasks '
    'include adopting the responseDocument unified response model for all API endpoints to ensure consistent output format, integrating '
    'Florence-2 for document layout analysis and region proposal to improve text detection accuracy, implementing the chunking strategies '
    '(especially sliding window and NLP sentence chunking) for extracted text preparation, and adding image annotation capabilities '
    'using the draw_ocr_bboxes and plot_bbox utilities for improved visual feedback in the correction workflow. These changes '
    'directly enhance the core OCR accuracy and user experience without requiring new infrastructure.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>6.2 Phase 2: Multi-Modal Expansion (Medium-Term)</b>', styles['H2']))
story.append(Paragraph(
    'The second phase extends the system\'s input modalities beyond handwritten/printed text. This involves integrating Whisper '
    'for audio transcription to support voice dictation processing, implementing document pre-processing via LibreOffice headless '
    'mode and Marker for handling diverse input formats (PDF, Word, PowerPoint), and adding a web crawling module for medical '
    'literature ingestion and drug database cross-referencing. This phase requires additional model loading infrastructure (similar '
    'to OmniParse\'s SharedState pattern) and potentially additional GPU memory allocation. The Whisper integration should leverage '
    'the existing Celery task infrastructure for asynchronous processing of audio files, while the document pre-processing pipeline '
    'should be integrated as a middleware step in the existing upload router.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>6.3 Phase 3: Platform Maturity (Long-Term)</b>', styles['H2']))
story.append(Paragraph(
    'The third phase focuses on platform-level improvements that establish the medical OCR system as a comprehensive medical data '
    'processing platform. This includes developing a formal Python SDK following the AsyncOmniParse pattern for easier third-party '
    'integration, implementing conditional router loading for optimized deployment configurations, adding a Gradio-based development '
    'interface for rapid pipeline testing, and building a batch processing system for handling large volumes of medical documents. '
    'Additionally, this phase should explore integrating OmniParse\'s LLM-based content extraction capabilities (the web module\'s '
    'LLMExtractionStrategy) for intelligent medical document understanding, though this would require careful consideration of data '
    'privacy requirements in healthcare settings. The platform maturity phase would also benefit from adopting OmniParse\'s Docker '
    'deployment patterns with modular model loading based on available GPU resources.',
    styles['Body']
))
story.append(Spacer(1, 6))

# Roadmap priority table
rp_data = [
    [Paragraph('<b>Phase</b>', header_style), Paragraph('<b>Timeline</b>', header_style), Paragraph('<b>Features</b>', header_style), Paragraph('<b>Complexity</b>', header_style), Paragraph('<b>Impact</b>', header_style)],
    [Paragraph('Phase 1', cell_center), Paragraph('1-2 months', cell_center), Paragraph('Unified response model, Florence-2 layout, chunking, image annotation', cell_style), Paragraph('Medium', cell_center), Paragraph('High', cell_center)],
    [Paragraph('Phase 2', cell_center), Paragraph('3-4 months', cell_center), Paragraph('Whisper audio, document pre-processing, web crawling', cell_style), Paragraph('High', cell_center), Paragraph('High', cell_center)],
    [Paragraph('Phase 3', cell_center), Paragraph('5-6 months', cell_center), Paragraph('Python SDK, conditional loading, batch processing, Gradio dev UI', cell_style), Paragraph('Medium', cell_center), Paragraph('Medium', cell_center)],
]
story.append(Spacer(1, 12))
t = make_table(rp_data, [avail_w*0.10, avail_w*0.13, avail_w*0.44, avail_w*0.14, avail_w*0.10], avail_w)
story.append(t)
story.append(Paragraph('Table 6: Recommended integration roadmap for OmniParse features', styles['Caption']))

# ═══════════════════════════════════════════
# 7. TECHNICAL CONSIDERATIONS AND RISKS
# ═══════════════════════════════════════════
story.extend(add_major_section('<b>7. Technical Considerations and Risks</b>', styles['H1']))

story.append(Paragraph('<b>7.1 License Compatibility</b>', styles['H2']))
story.append(Paragraph(
    'A critical consideration for integrating OmniParse components into the Medical OCR project is license compatibility. OmniParse '
    'is licensed under GPL-3.0, which has strong copyleft requirements. However, the underlying models have separate licenses: '
    'Surya OCR and Marker model weights are licensed under CC-BY-NC-SA-4.0 with a commercial use exception for organizations '
    'with less than $5M USD in gross revenue and less than $5M in lifetime VC/angel funding. The Florence-2 model from Microsoft '
    'uses the MIT license. Whisper from OpenAI uses the MIT license. For the Medical OCR project, which appears to be a research '
    'and healthcare-focused initiative, the GPL-3.0 copyleft requirements should be carefully evaluated, particularly if the project '
    'may eventually be used in commercial healthcare applications. The safest approach is to adopt OmniParse\'s architectural patterns '
    'and design principles while re-implementing the specific algorithms, rather than directly copying GPL-licensed code.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>7.2 GPU Resource Requirements</b>', styles['H2']))
story.append(Paragraph(
    'OmniParse\'s full model stack requires a minimum of 8-10 GB of GPU VRAM, which is a significant resource consideration. '
    'The Medical OCR project\'s existing model requirements (PaddleOCR + TrOCR) already consume substantial GPU memory. Adding '
    'Florence-2 (approximately 0.77B parameters for the base model) and potentially Whisper would increase the total memory '
    'footprint considerably. OmniParse\'s approach of conditional model loading based on command-line flags provides a useful '
    'pattern for managing this constraint. The medical OCR system could implement a similar approach, allowing deployment '
    'configurations that load only the required models based on the use case. For example, a prescription-only deployment would '
    'load PaddleOCR + TrOCR + Florence-2, while a full deployment would additionally load Whisper for audio processing. The '
    'Terraform and K8s deployment infrastructure already present in the medical OCR project provides the foundation for managing '
    'these heterogeneous deployment configurations.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>7.3 Arabic Language Support</b>', styles['H2']))
story.append(Paragraph(
    'Both OmniParse and the Medical OCR project face challenges with Arabic language support, though in different ways. The Medical '
    'OCR project is specifically designed for Arabic medical handwriting, with Arabic Soundex for phonetic matching and RTL text '
    'handling throughout the stack. OmniParse, however, is primarily optimized for English content. The Surya OCR models have '
    'limited Arabic support, and the Florence-2 model\'s OCR capabilities may not perform optimally on Arabic script, particularly '
    'handwritten Arabic medical text. The NLP chunking strategies in OmniParse use NLTK\'s English-centric tokenizers, which '
    'would need to be replaced with Arabic-appropriate tokenizers. The Whisper model does support Arabic transcription, which is a '
    'positive consideration for the audio integration. Any integration of OmniParse components would require thorough testing '
    'with Arabic medical text and likely fine-tuning of the underlying models for the specific Arabic medical domain.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph('<b>7.4 Data Privacy and Healthcare Compliance</b>', styles['H2']))
story.append(Paragraph(
    'Integrating web crawling and LLM-based content extraction capabilities from OmniParse into a medical system raises important '
    'data privacy considerations. The medical OCR system handles sensitive patient information, and any external data fetching or '
    'LLM processing must comply with healthcare data regulations (such as HIPAA, GDPR, or regional equivalents). OmniParse\'s '
    'LLM extraction strategy in the web module sends HTML content to external LLM providers (OpenAI, Groq, Anthropic), which '
    'would not be acceptable for processing patient data. If the web crawling integration is pursued, it should be strictly limited '
    'to public medical literature and drug databases, with clear data flow boundaries ensuring that patient data is never sent to '
    'external services. The audio processing integration with Whisper is safer in this regard, as Whisper runs entirely locally, '
    'but the transcribed content (medical dictation) would still be classified as patient data requiring appropriate protection.',
    styles['Body']
))
story.append(Spacer(1, 6))

# ═══════════════════════════════════════════
# 8. COMPARATIVE ANALYSIS
# ═══════════════════════════════════════════
story.extend(add_major_section('<b>8. Comparative Analysis: OmniParse vs. Medical OCR</b>', styles['H1']))

story.append(Paragraph(
    'The following table provides a comprehensive feature-by-feature comparison between OmniParse and the Medical Handwriting OCR '
    'project, highlighting areas of overlap, complementarity, and integration potential. This comparison is essential for '
    'understanding which OmniParse features represent genuine enhancements versus which capabilities the medical OCR project '
    'already surpasses.',
    styles['Body']
))
story.append(Spacer(1, 6))

comp_data = [
    [Paragraph('<b>Feature</b>', header_style), Paragraph('<b>OmniParse</b>', header_style), Paragraph('<b>Medical OCR</b>', header_style), Paragraph('<b>Gap/Opportunity</b>', header_style)],
    [Paragraph('OCR Engine', cell_style), Paragraph('Surya OCR + Florence-2', cell_style), Paragraph('PaddleOCR + TrOCR', cell_style), Paragraph('Complementary - multi-engine fusion', cell_style)],
    [Paragraph('Language Support', cell_style), Paragraph('English primary', cell_style), Paragraph('Arabic primary with Soundex', cell_style), Paragraph('Medical OCR leads here', cell_style)],
    [Paragraph('Document Formats', cell_style), Paragraph('PDF, DOC, PPT, images', cell_style), Paragraph('Images (uploaded)', cell_style), Paragraph('Medical OCR can expand formats', cell_style)],
    [Paragraph('Audio Processing', cell_style), Paragraph('Whisper transcription', cell_style), Paragraph('Not implemented', cell_style), Paragraph('High-value addition', cell_style)],
    [Paragraph('Web Crawling', cell_style), Paragraph('Selenium + HTML parser', cell_style), Paragraph('Not implemented', cell_style), Paragraph('Medium-value addition', cell_style)],
    [Paragraph('Text Chunking', cell_style), Paragraph('5 strategies', cell_style), Paragraph('Not implemented', cell_style), Paragraph('High-value for RAG', cell_style)],
    [Paragraph('Suggestion Engine', cell_style), Paragraph('Not implemented', cell_style), Paragraph('6 strategies + UMLS/SNOMED', cell_style), Paragraph('Medical OCR leads here', cell_style)],
    [Paragraph('Continual Learning', cell_style), Paragraph('Not implemented', cell_style), Paragraph('EWC + Replay Buffer', cell_style), Paragraph('Medical OCR leads here', cell_style)],
    [Paragraph('Database/ORM', cell_style), Paragraph('Not implemented (stateless)', cell_style), Paragraph('PostgreSQL + 7 models', cell_style), Paragraph('Medical OCR leads here', cell_style)],
    [Paragraph('Security', cell_style), Paragraph('CORS only', cell_style), Paragraph('6 middleware + rate limiting', cell_style), Paragraph('Medical OCR leads here', cell_style)],
    [Paragraph('Deployment', cell_style), Paragraph('Docker (single)', cell_style), Paragraph('Docker + K8s + Terraform', cell_style), Paragraph('Medical OCR leads here', cell_style)],
    [Paragraph('UI', cell_style), Paragraph('Gradio (development)', cell_style), Paragraph('React/Vite + HTML MVP', cell_style), Paragraph('Medical OCR leads here', cell_style)],
    [Paragraph('Response Model', cell_style), Paragraph('Unified responseDocument', cell_style), Paragraph('Varies by endpoint', cell_style), Paragraph('OmniParse pattern worth adopting', cell_style)],
    [Paragraph('Python SDK', cell_style), Paragraph('AsyncOmniParse client', cell_style), Paragraph('API docs only', cell_style), Paragraph('OmniParse pattern worth adopting', cell_style)],
]
story.append(Spacer(1, 12))
t = make_table(comp_data, [avail_w*0.18, avail_w*0.24, avail_w*0.28, avail_w*0.30], avail_w)
story.append(t)
story.append(Paragraph('Table 7: Comprehensive feature comparison between OmniParse and Medical Handwriting OCR', styles['Caption']))

# ═══════════════════════════════════════════
# 9. CONCLUSION
# ═══════════════════════════════════════════
story.extend(add_major_section('<b>9. Conclusion</b>', styles['H1']))

story.append(Paragraph(
    'This study has provided an in-depth architectural analysis of the OmniParse project and identified 10 specific integration '
    'opportunities that can enhance the Medical Handwriting OCR system. The analysis reveals a complementary relationship between '
    'the two projects: OmniParse excels in multi-modal data ingestion, flexible document processing, and clean architectural patterns, '
    'while the Medical OCR project leads in domain-specific medical intelligence, security infrastructure, production deployment, '
    'and Arabic language support.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph(
    'The highest-impact integrations identified in this study include: (1) adopting OmniParse\'s unified response model pattern '
    'for consistent API output, (2) integrating Florence-2 for enhanced document layout analysis and region detection, '
    '(3) implementing the text chunking framework for RAG pipeline preparation, and (4) adding Whisper-based audio transcription '
    'for voice dictation support. These four enhancements alone would significantly expand the system\'s capabilities without '
    'requiring fundamental architectural changes. The proposed three-phase roadmap provides a practical path for implementing '
    'these integrations, starting with core OCR enhancements and progressing toward a comprehensive multi-modal medical data '
    'processing platform.',
    styles['Body']
))
story.append(Spacer(1, 6))

story.append(Paragraph(
    'The study also highlights important considerations around license compatibility (GPL-3.0), GPU resource management, Arabic '
    'language support gaps in OmniParse\'s models, and healthcare data privacy requirements. These factors must be carefully '
    'addressed in the integration design to ensure compliance and maintain the medical OCR system\'s production-grade reliability. '
    'Ultimately, OmniParse serves as an excellent architectural reference and feature inspiration source, and selective adoption '
    'of its design patterns and processing capabilities will accelerate the evolution of the Medical Handwriting OCR system into '
    'a truly comprehensive medical data understanding platform.',
    styles['Body']
))
story.append(Spacer(1, 6))

# ── References ──
story.extend(add_major_section('<b>References</b>', styles['H1']))

refs = [
    '[1] Adithya S K, "OmniParse: Parse Any Document and Convert to Actionable Data for LLMs," GitHub Repository, 2024. Available: https://github.com/adithya-s-k/omniparse',
    '[2] VikParuchuri, "Marker: Convert PDF to Markdown," GitHub Repository, 2024. Available: https://github.com/VikParuchuri/marker',
    '[3] VikParuchuri, "Surya OCR Series," GitHub Repository, 2024. Available: https://github.com/VikParuchuri/surya',
    '[4] Microsoft, "Florence-2: A Unified Vision-Language Model," arXiv preprint, 2024.',
    '[5] OpenAI, "Whisper: Robust Speech Recognition via Large-Scale Weak Supervision," arXiv preprint, 2023.',
    '[6] DrAbdulmalek, "Medical Handwriting OCR System v3.2.0," GitHub Repository, 2026. Available: https://github.com/DrAbdulmalek/medical-handwriting-ocr',
]
for ref in refs:
    story.append(Paragraph(ref, ParagraphStyle(
        name='Ref', fontName='Times New Roman', fontSize=9.5,
        leading=15, alignment=TA_LEFT, textColor=TEXT_PRIMARY,
        leftIndent=24, firstLineIndent=-24, spaceBefore=2, spaceAfter=2
    )))

# ── Build ──
doc.multiBuild(story)
print(f"Body PDF generated: {OUTPUT}")
